#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

PROG=/usr/bin/not-jira
CONFIG_DIR=/etc/not-jira
CONFIG_FILE=$CONFIG_DIR/config.yaml

start_service() {
    [ -d "$CONFIG_DIR" ] || mkdir -p "$CONFIG_DIR"

    if [ ! -f "$CONFIG_FILE" ]; then
        echo "Error: $CONFIG_FILE not found!"
        return 1
    fi

    procd_open_instance
    procd_set_param command $PROG -config "$CONFIG_FILE"
    
    # Ограничение потребления оперативной памяти рантаймом Go
    procd_set_param env GOMEMLIMIT=20MiB GOGC=50
    
    # Рабочая директория (здесь будет храниться bot.db)
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root
    
    procd_close_instance
}

stop_service() {
    killall not-jira
}
